### ISSUE TITLE
latest changes in sonarqube (v 1.6.0) breaks pipelines

### ISSUE THREAD

**Issue by abalasu1** [ibm-garage-cloud/ibm-garage-iteration-zero#135]
Latest version of sonarqube module breaks all pipelines.

Error while running pipelines:
error is: ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.ProjectLock
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at org.sonar.core.platform.ComponentContainer.getComponentByType(ComponentContainer.java:281)
	at org.sonar.s

**Comment by seansund** [comment]
I've reverted the sonarqube module for now in release v1.7.1 of the toolkit until the sonarqube issue is resolved
